info:
    app:
      name : DataSecurityConfig
      description : Config
  spring:
      config:
          activate:
              on-profile : default
SALT_KEY : Data_Security
OWNER_PASSWORD : DmiN
